<Project>
	<PropertyGroup>
		<NetFxVersion>net48</NetFxVersion>
		<NetCoreVersion>net8.0</NetCoreVersion>
		<FileVersion>4.1.0.8</FileVersion>
		<WisejPackageName>Wisej-4</WisejPackageName>
		<WisejVersion>4.1.*-*</WisejVersion>
		<SdmVersion>4.1.*-*</SdmVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true' and '$(TargetFramework)' == '$(NetFxVersion)'">
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	</PropertyGroup>
	<ItemGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true' and '$(TargetFramework)' == '$(NetFxVersion)'">
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
	</ItemGroup>
</Project>
