<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.1.0.5</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Templates\**" />
    <Compile Remove="Wisej.TourPanel.Templates\**" />
    <EmbeddedResource Remove="Templates\**" />
    <EmbeddedResource Remove="Wisej.TourPanel.Templates\**" />
    <None Remove="Templates\**" />
    <None Remove="Wisej.TourPanel.Templates\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Platform\wisej.web.ext.TourPanel.js" />
    <None Remove="Themes\TourPanel.mixin.theme" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Themes\TourPanel.mixin.theme" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Platform\wisej.web.ext.TourPanel.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
    <PackageReference Include="$(WisejPackageName)-RibbonBar" Version="$(WisejVersion)" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>
