<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.0.12.30</FileVersion>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Templates\Visual C#\ColumnFilterPanel\ColumnFilterPanel.cs" />
    <Compile Remove="Templates\Visual C#\ColumnFilterPanel\ColumnFilterPanel.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ColumnFilter.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ColumnFilter.bmp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Templates\Visual C#\ColumnFilterPanel\ColumnFilterPanel.cs" />
    <None Include="Templates\Visual C#\ColumnFilterPanel\ColumnFilterPanel.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.7" />
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Messages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Messages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Messages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetDir)Wisej.Web.Ext.*.dll&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>
