<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <!--<ItemGroup Condition="'$(TargetFramework)'=='net48'">
  <Reference Include="System.Windows.Forms" />
  <Reference Include="System.Design" />
</ItemGroup>-->
  <ItemGroup>
    <None Remove="Platform\wisej.web.ext.ApexChartsWidget.js" />
    <None Remove="Wisej.Web.Ext.ApexCharts.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Platform\wisej.web.ext.ApexChartsWidget.js" />
    <EmbeddedResource Include="Wisej.Web.Ext.ApexCharts.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>