<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0;net8.0-android;net8.0-ios;net8.0-maccatalyst;net8.0-windows10.0.19041.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>3.5.36.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ZXing.NET\renderer\GeometryRenderer.cs" />
    <Compile Remove="ZXing.NET\renderer\RawRenderer.cs" />
    <Compile Remove="ZXing.NET\renderer\WriteableBitmapRenderer.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Barcode.bmp" />
    <None Remove="Platform\wisej.web.ext.BarcodeReader.js" />
    <None Remove="JavaScript\ZXing.BrowserMultiFormatReader.min.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Barcode.bmp" />
    <EmbeddedResource Include="Platform\wisej.web.ext.BarcodeReader.js" />
    <EmbeddedResource Include="JavaScript\ZXing.BrowserMultiFormatReader.min.js" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Wisej-3" Version="3.5.*-*" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>