<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.1.0.44</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ZXing.NET\renderer\GeometryRenderer.cs" />
    <Compile Remove="ZXing.NET\renderer\RawRenderer.cs" />
    <Compile Remove="ZXing.NET\renderer\WriteableBitmapRenderer.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Barcode.bmp" />
    <None Remove="Platform\wisej.web.ext.BarcodeReader.js" />
    <None Remove="JavaScript\ZXing.BrowserMultiFormatReader.min.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Barcode.bmp" />
    <EmbeddedResource Include="Platform\wisej.web.ext.BarcodeReader.js" />
    <EmbeddedResource Include="JavaScript\ZXing.BrowserMultiFormatReader.min.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>