<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-windows10.0.19041.0;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.1.0.6</FileVersion>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="JavaScript\panzoom.min.js" />
    <None Remove="JavaScript\startup.js" />
    <None Remove="JavaScript\mermaid.min.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="JavaScript\panzoom.min.js" />
    <EmbeddedResource Include="JavaScript\startup.js" />
    <EmbeddedResource Include="JavaScript\mermaid.min.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
    <PackageReference Include="$(WisejPackageName)-Html2Canvas" Version="$(WisejVersion)" />
  </ItemGroup>
  <Target Name="CopyFilesToBin" AfterTargets="PostBuildEvent">
	<ItemGroup>
	  <FilesToCopy Include="$(TargetDir)Wisej.Web.Ext.Mermaid.dll" />
	  <FilesToCopy Include="$(TargetDir)Wisej.Web.Ext.Mermaid.xml" />
	</ItemGroup>

	<Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(ProjectDir)..\bin\$(TargetFramework)\" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" />
  </Target>
</Project>