<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	  <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<SignAssembly>true</SignAssembly>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
		<EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
		<LangVersion>latest</LangVersion>
		<FileVersion>4.1.0.28</FileVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="JavaScript\chartjs-adapter-date-fns-3.0.0.bundle.min.js" />
		<None Remove="JavaScript\chartjs-plugin-datalabels.js" />
		<None Remove="JavaScript\easingEffects.js" />
		<None Remove="JavaScript\moment-with-locales-2.29.4.js" />
		<None Remove="JavaScript\startup.js" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="ChartJS4.bmp" />
		<EmbeddedResource Include="JavaScript\chart.min.js" />
		<EmbeddedResource Include="JavaScript\chartjs-adapter-date-fns-3.0.0.bundle.min.js" />
		<EmbeddedResource Include="JavaScript\chartjs-plugin-datalabels.js" />
		<EmbeddedResource Include="JavaScript\easingEffects.js" />
		<EmbeddedResource Include="JavaScript\moment-with-locales-2.29.4.js" />
		<EmbeddedResource Include="JavaScript\startup.js" />
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)'=='net48' ">
		<Reference Include="System.Design" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)'=='net48' ">
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)'!='net48'">
		<Compile Remove="Design\**" />
	</ItemGroup>
</Project>
