<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.0.12.2</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Chart.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Chart.bmp" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>