///////////////////////////////////////////////////////////////////////////////
//
// (C) 2020 ICE TEA GROUP LLC - ALL RIGHTS RESERVED
//
// 
//
// ALL INFORMATION CONTAINED HEREIN IS, AND REMAINS
// THE PROPERTY OF ICE TEA GROUP LLC AND ITS SUPPLIERS, IF ANY.
// THE INTELLECTUAL PROPERTY AND TECHNICAL CONCEPTS CONTAINED
// HEREIN ARE PROPRIETARY TO ICE TEA GROUP LLC AND ITS SUPPLIERS
// AND MAY BE COVERED BY U.S. AND FOREIGN PATENTS, PATENT IN PROCESS, AND
// ARE PROTECTED BY TRADE SECRET OR COPYRIGHT LAW.
//
// DISSEMINATION OF THIS INFORMATION OR REPRODUCTION OF THIS MATERIAL
// IS STRICTLY FORBIDDEN UNLESS PRIOR WRITTEN PERMISSION IS OBTAINED
// FROM ICE TEA GROUP LLC.
//
///////////////////////////////////////////////////////////////////////////////

namespace Wisej.Web.Ext.PrintPreview
{
	/// <summary>
	/// Selects the type of <see cref="PrintPreviewControl"/> to use.
	/// </summary>
	public enum PrintPreviewDialogViewerType
	{
		/// <summary>
		/// Uses the embedded PDFJS viewer.
		/// </summary>
		PDF,

		/// <summary>
		/// Uses the Windows Meta File (WMF) viewer to draw the pages 
		/// generated by the <see cref="System.Drawing.Printing.PreviewPrintController"/>.
		/// </summary>
		WMF
	}
}