<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFxVersion);$(NetCoreVersion);$(NetCoreVersion)-windows;$(NetCoreVersion)-android;$(NetCoreVersion)-ios;$(NetCoreVersion)-maccatalyst;$(NetCoreVersion)-windows10.0.19041.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyOriginatorKeyFile>extension.snk</AssemblyOriginatorKeyFile>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <FileVersion>4.0.8.18</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ChartJS3.bmp" />
    <None Remove="JavaScript\chart-3.5.0.js" />
    <None Remove="JavaScript\chartjs-plugin-datalabels.js" />
    <None Remove="JavaScript\moment-with-locales-2.29.4.js" />
    <None Remove="JavaScript\startup.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ChartJS3.bmp" />
    <EmbeddedResource Include="JavaScript\chart-3.5.0.js" />
    <EmbeddedResource Include="JavaScript\chartjs-plugin-datalabels.js" />
    <EmbeddedResource Include="JavaScript\moment-with-locales-2.29.4.js" />
    <EmbeddedResource Include="JavaScript\startup.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="$(WisejPackageName)" Version="$(WisejVersion)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'!='net48'">
    <Compile Remove="Design\**" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <Reference Include="System.Design" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\bin&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetName).xml&quot; &quot;$(ProjectDir)..\bin\$(TargetFramework)\&quot; /s /y /c&#xD;&#xA;" />
  </Target>
</Project>